# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/simple_led/simple_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led || ORIG_REF_NAME==simple_led} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_processing_system7_0_0/simple_led_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_processing_system7_0_0 || ORIG_REF_NAME==simple_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_axi_gpio_0_0/simple_led_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_axi_gpio_0_0 || ORIG_REF_NAME==simple_led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_ps7_0_axi_periph_0/simple_led_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==simple_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_rst_ps7_0_100M_0/simple_led_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_rst_ps7_0_100M_0 || ORIG_REF_NAME==simple_led_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_axi_gpio_1_0/simple_led_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_axi_gpio_1_0 || ORIG_REF_NAME==simple_led_axi_gpio_1_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_xbar_0/simple_led_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_xbar_0 || ORIG_REF_NAME==simple_led_xbar_0} -quiet] -quiet

# IP: bd/simple_led/ip/simple_led_auto_pc_0/simple_led_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_led_auto_pc_0 || ORIG_REF_NAME==simple_led_auto_pc_0} -quiet] -quiet

# XDC: bd/simple_led/simple_led_ooc.xdc
