# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/bop/Documents/GitHub/FPGA/simle_start/simle_start.srcs/sources_1/bd/simple_led/ip/simple_led_processing_system7_0_0/simple_led_processing_system7_0_0.xci
# IP: The module: 'simple_led_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bop/Documents/GitHub/FPGA/simle_start/simle_start.srcs/sources_1/bd/simple_led/ip/simple_led_processing_system7_0_0/simple_led_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_led_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/bop/Documents/GitHub/FPGA/simle_start/simle_start.srcs/sources_1/bd/simple_led/ip/simple_led_processing_system7_0_0/simple_led_processing_system7_0_0.xci
# IP: The module: 'simple_led_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bop/Documents/GitHub/FPGA/simle_start/simle_start.srcs/sources_1/bd/simple_led/ip/simple_led_processing_system7_0_0/simple_led_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simple_led_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
