# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rom_read/rom_read.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read || ORIG_REF_NAME==rom_read} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_ROM_0_0/rom_read_ROM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_ROM_0_0 || ORIG_REF_NAME==rom_read_ROM_0_0} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_axi_bram_ctrl_0_0/rom_read_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_axi_bram_ctrl_0_0 || ORIG_REF_NAME==rom_read_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_processing_system7_0_0/rom_read_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_processing_system7_0_0 || ORIG_REF_NAME==rom_read_processing_system7_0_0} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_axi_mem_intercon_0/rom_read_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_axi_mem_intercon_0 || ORIG_REF_NAME==rom_read_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_rst_ps7_0_100M_0/rom_read_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_rst_ps7_0_100M_0 || ORIG_REF_NAME==rom_read_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/rom_read/ip/rom_read_auto_pc_0/rom_read_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_read_auto_pc_0 || ORIG_REF_NAME==rom_read_auto_pc_0} -quiet] -quiet

# XDC: bd/rom_read/rom_read_ooc.xdc
