# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/rom_read_ROM_0_0.xci
# IP: The module: 'rom_read_ROM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_read_ROM_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/rom_read_ROM_0_0.xci
# IP: The module: 'rom_read_ROM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/bop/Documents/GitHub/FPGA/ROM_test/ROM_test.srcs/sources_1/bd/rom_read/ip/rom_read_ROM_0_0/src/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_read_ROM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
